name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 1-18 * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Health Endpoint
        run: |
          curl -L https://campusops-ai.onrender.com